#include "runtime.h"
#include "emitter.h"

void runtime_emit_math(void) {
    emitln("__memcpy:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    MOV 8(R4), R2");
    emitln(".Lmemcpy_loop:");
    emitln("    TST R2");
    emitln("    BEQ .Lmemcpy_end");
    emitln("    MOVB (R1)+, (R0)+");
    emitln("    DEC R2");
    emitln("    BR .Lmemcpy_loop");
    emitln(".Lmemcpy_end:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("__not:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R1");
    emitln("    MOV #0xFFFF, R0");
    emitln("    BIC R1, R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("__and:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    MOV #0xFFFF, R2");
    emitln("    BIC R0, R2");
    emitln("    MOV #0xFFFF, R3");
    emitln("    BIC R1, R3");
    emitln("    MOV R2, R0");
    emitln("    BIS R3, R0");
    emitln("    MOV #0xFFFF, R1");
    emitln("    BIC R0, R1");
    emitln("    MOV R1, R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("__or:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    BIS R1, R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("__xor:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    MOV R0, R2");
    emitln("    BIC R1, R2");
    emitln("    MOV R1, R3");
    emitln("    BIC R0, R3");
    emitln("    BIS R2, R3");
    emitln("    MOV R3, R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("__shl:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln(".Lshl_loop:");
    emitln("    TST R1");
    emitln("    BEQ .Lshl_end");
    emitln("    ASL R0");
    emitln("    DEC R1");
    emitln("    BR .Lshl_loop");
    emitln(".Lshl_end:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("__shr:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln(".Lshr_loop:");
    emitln("    TST R1");
    emitln("    BEQ .Lshr_end");
    emitln("    ASR R0");
    emitln("    DEC R1");
    emitln("    BR .Lshr_loop");
    emitln(".Lshr_end:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("__mul:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    CLR R2");
    emitln("    MOV R0, R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    BIC #0xFFFE, R3");
    emitln("    CMP #0, R3");
    emitln("    BEQ .Lmul_a_pos");
    emitln("    MOV R0, R3");
    emitln("    CLR R0");
    emitln("    SUB R3, R0");
    emitln("    MOV #1, R3");
    emitln("    SUB R2, R3");
    emitln("    MOV R3, R2");
    emitln(".Lmul_a_pos:");
    emitln("    MOV R1, R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    BIC #0xFFFE, R3");
    emitln("    CMP #0, R3");
    emitln("    BEQ .Lmul_b_pos");
    emitln("    MOV R1, R3");
    emitln("    CLR R1");
    emitln("    SUB R3, R1");
    emitln("    MOV #1, R3");
    emitln("    SUB R2, R3");
    emitln("    MOV R3, R2");
    emitln(".Lmul_b_pos:");
    emitln("    CLR R3");
    emitln(".Lmul_loop:");
    emitln("    CMP #0, R1");
    emitln("    BEQ .Lmul_done");
    emitln("    ADD R0, R3");
    emitln("    DEC R1");
    emitln("    BR .Lmul_loop");
    emitln(".Lmul_done:");
    emitln("    MOV R3, R0");
    emitln("    CMP #0, R2");
    emitln("    BEQ .Lmul_end");
    emitln("    MOV R0, R3");
    emitln("    CLR R0");
    emitln("    SUB R3, R0");
    emitln(".Lmul_end:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("__div:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    SUB #2, R6");
    emitln("    CLR -2(R4)");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    MOV R0, R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    BIC #0xFFFE, R3");
    emitln("    CMP #0, R3");
    emitln("    BEQ .Ldiv_a_pos");
    emitln("    MOV R0, R3");
    emitln("    CLR R0");
    emitln("    SUB R3, R0");
    emitln("    MOV -2(R4), R2");
    emitln("    MOV #1, R3");
    emitln("    SUB R2, R3");
    emitln("    MOV R3, -2(R4)");
    emitln(".Ldiv_a_pos:");
    emitln("    MOV R1, R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    BIC #0xFFFE, R3");
    emitln("    CMP #0, R3");
    emitln("    BEQ .Ldiv_b_pos");
    emitln("    MOV R1, R3");
    emitln("    CLR R1");
    emitln("    SUB R3, R1");
    emitln("    MOV -2(R4), R2");
    emitln("    MOV #1, R3");
    emitln("    SUB R2, R3");
    emitln("    MOV R3, -2(R4)");
    emitln(".Ldiv_b_pos:");
    emitln("    CMP #0, R1");
    emitln("    BEQ .Ldiv_zero");
    emitln("    CLR R2");
    emitln(".Ldiv_loop:");
    emitln("    MOV R0, R3");
    emitln("    SUB R1, R3");
    emitln("    MOV R3, R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    ASR R0");
    emitln("    BIC #0xFFFE, R0");
    emitln("    CMP #0, R0");
    emitln("    BNE .Ldiv_done");
    emitln("    MOV R3, R0");
    emitln("    INC R2");
    emitln("    BR .Ldiv_loop");
    emitln(".Ldiv_done:");
    emitln("    MOV R2, R0");
    emitln("    MOV -2(R4), R3");
    emitln("    CMP #0, R3");
    emitln("    BEQ .Ldiv_end");
    emitln("    MOV R0, R3");
    emitln("    CLR R0");
    emitln("    SUB R3, R0");
    emitln(".Ldiv_end:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");
    emitln(".Ldiv_zero:");
    emitln("    CLR R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("__mod:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    SUB #2, R6");
    emitln("    CLR -2(R4)");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    MOV R0, R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    ASR R3");
    emitln("    BIC #0xFFFE, R3");
    emitln("    CMP #0, R3");
    emitln("    BEQ .Lmod_a_pos");
    emitln("    MOV R0, R3");
    emitln("    CLR R0");
    emitln("    SUB R3, R0");
    emitln("    MOV #1, R3");
    emitln("    SUB -2(R4), R3");
    emitln("    MOV R3, -2(R4)");
    emitln(".Lmod_a_pos:");
    emitln("    CMP #0, R1");
    emitln("    BEQ .Lmod_zero");
    emitln(".Lmod_loop:");
    emitln("    MOV R0, R3");
    emitln("    SUB R1, R3");
    emitln("    MOV R3, R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    ASR R2");
    emitln("    BIC #0xFFFE, R2");
    emitln("    CMP #0, R2");
    emitln("    BNE .Lmod_done");
    emitln("    MOV R3, R0");
    emitln("    BR .Lmod_loop");
    emitln(".Lmod_done:");
    emitln("    MOV -2(R4), R3");
    emitln("    CMP #0, R3");
    emitln("    BEQ .Lmod_end");
    emitln("    MOV R0, R3");
    emitln("    CLR R0");
    emitln("    SUB R3, R0");
    emitln(".Lmod_end:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");
    emitln(".Lmod_zero:");
    emitln("    CLR R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");
}
