#include "runtime.h"
#include "emitter.h"

void runtime_emit_format(void) {
    emitln("print_uint:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    TRAP #7");
    emitln("    MOV #0, R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("print_int:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    TRAP #4");
    emitln("    MOV #0, R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("print_hex:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    TRAP #6");
    emitln("    MOV #0, R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("scanf_int:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    TRAP #9");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("scanf_hex:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    TRAP #10");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("readline:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    TRAP #5");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("printf:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV #1, R0");
    emitln("    MOV R0, -(R6)");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, vfprintf");
    emitln("    ADD #4, R6");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("fprintf:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 6(R4), R0");
    emitln("    MOV R0, -(R6)");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, vfprintf");
    emitln("    ADD #4, R6");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("sprintf:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV R0, -(R6)");
    emitln("    MOV 6(R4), R0");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, vsprintf");
    emitln("    ADD #4, R6");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("vfprintf:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    SUB #2, R6");
    emitln("    CLR -2(R4)");
    emitln("    MOV 6(R4), R1");
    emitln("    MOV 8(R4), R2");
    emitln(".Lfmt_loop:");
    emitln("    MOVB (R1)+, R0");
    emitln("    BEQ .Lfmt_done");
    emitln("    CMP #0x0025, R0");
    emitln("    BEQ .Lfmt_conv");
    emitln("    MOV 4(R4), R3");
    emitln("    MOV R0, -(R6)");
    emitln("    MOV R3, -(R6)");
    emitln("    JSR R5, fputc");
    emitln("    ADD #4, R6");
    emitln("    INC -2(R4)");
    emitln("    BR .Lfmt_loop");
    emitln(".Lfmt_conv:");
    emitln("    MOVB (R1)+, R0");
    emitln("    BEQ .Lfmt_done");
    emitln("    CMP #0x0064, R0");
    emitln("    BEQ .Lfmt_int");
    emitln("    CMP #0x0075, R0");
    emitln("    BEQ .Lfmt_uint");
    emitln("    CMP #0x0078, R0");
    emitln("    BEQ .Lfmt_hex");
    emitln("    CMP #0x0063, R0");
    emitln("    BEQ .Lfmt_char");
    emitln("    CMP #0x0073, R0");
    emitln("    BEQ .Lfmt_str");
    emitln("    BR .Lfmt_loop");
    emitln(".Lfmt_int:");
    emitln("    MOV (R2)+, R0");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, print_int");
    emitln("    ADD #2, R6");
    emitln("    INC -2(R4)");
    emitln("    BR .Lfmt_loop");
    emitln(".Lfmt_uint:");
    emitln("    MOV (R2)+, R0");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, print_uint");
    emitln("    ADD #2, R6");
    emitln("    INC -2(R4)");
    emitln("    BR .Lfmt_loop");
    emitln(".Lfmt_hex:");
    emitln("    MOV (R2)+, R0");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, print_hex");
    emitln("    ADD #2, R6");
    emitln("    INC -2(R4)");
    emitln("    BR .Lfmt_loop");
    emitln(".Lfmt_char:");
    emitln("    MOV (R2)+, R0");
    emitln("    MOV R0, -(R6)");
    emitln("    MOV 4(R4), R1");
    emitln("    MOV R1, -(R6)");
    emitln("    JSR R5, fputc");
    emitln("    ADD #4, R6");
    emitln("    INC -2(R4)");
    emitln("    BR .Lfmt_loop");
    emitln(".Lfmt_str:");
    emitln("    MOV (R2)+, R0");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, puts");
    emitln("    ADD #2, R6");
    emitln("    INC -2(R4)");
    emitln("    BR .Lfmt_loop");
    emitln(".Lfmt_done:");
    emitln("    MOV -2(R4), R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("vsprintf:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV R0, -(R6)");
    emitln("    MOV 6(R4), R0");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, vfprintf");
    emitln("    ADD #4, R6");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");
}
