#include "runtime.h"
#include "emitter.h"

static void emit_data_load(const char *label, const char *reg, const char *tmp) {
    emitln("    MOV #%s, %s", label, tmp);
    emitln("    MOV (%s), %s", tmp, reg);
}

static void emit_data_load_byte(const char *label, const char *reg, const char *tmp) {
    emitln("    MOV #%s, %s", label, tmp);
    emitln("    MOVB (%s), %s", tmp, reg);
}

static void emit_data_store(const char *label, const char *reg, const char *tmp) {
    emitln("    MOV #%s, %s", label, tmp);
    emitln("    MOV %s, (%s)", reg, tmp);
}

static void emit_data_clr(const char *label, const char *tmp) {
    emitln("    MOV #%s, %s", label, tmp);
    emitln("    CLR (%s)", tmp);
}

void runtime_emit_fileio(void) {
    emitln("fopen:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    MOVB (R1), R2");
    emitln("    CMP #0x0072, R2");
    emitln("    BEQ .Lfopen_r");
    emitln("    CMP #0x0077, R2");
    emitln("    BEQ .Lfopen_w");
    emitln("    CMP #0x0061, R2");
    emitln("    BEQ .Lfopen_a");
    emitln("    CLR R1");
    emitln("    BR .Lfopen_mode");
    emitln(".Lfopen_r:");
    emitln("    CLR R1");
    emitln("    BR .Lfopen_chkplus");
    emitln(".Lfopen_w:");
    emitln("    MOV #1, R1");
    emitln("    BR .Lfopen_chkplus");
    emitln(".Lfopen_a:");
    emitln("    MOV #2, R1");
    emitln(".Lfopen_chkplus:");
    emitln("    MOV 6(R4), R2");
    emitln("    MOVB 1(R2), R2");
    emitln("    CMP #0x002B, R2");
    emitln("    BNE .Lfopen_mode");
    emitln("    MOV #3, R1");
    emitln(".Lfopen_mode:");
    emitln("    TRAP #20");
    emitln("    CMP #0xFFFF, R0");
    emitln("    BEQ .Lfopen_fail");
    emitln("    INC R0");
    emitln("    BR .Lfopen_ret");
    emitln(".Lfopen_fail:");
    emitln("    CLR R0");
    emitln(".Lfopen_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("fread:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 6(R4), R2");
    emitln("    MOV 8(R4), R3");
    emitln("    TST R2");
    emitln("    BEQ .Lfread_zero");
    emitln("    TST R3");
    emitln("    BEQ .Lfread_zero");
    emitln("    MOV R3, -(R6)");
    emitln("    MOV R2, -(R6)");
    emitln("    JSR R5, __mul");
    emitln("    ADD #4, R6");
    emitln("    MOV R0, R2");
    emitln("    MOV 10(R4), R0");
    emitln("    TST R0");
    emitln("    BEQ .Lfread_zero");
    emitln("    DEC R0");
    emitln("    MOV 4(R4), R1");
    emitln("    TRAP #21");
    emitln("    MOV 6(R4), R1");
    emitln("    CMP #1, R1");
    emitln("    BEQ .Lfread_ret");
    emitln("    MOV R1, -(R6)");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, __div");
    emitln("    ADD #4, R6");
    emitln(".Lfread_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");
    emitln(".Lfread_zero:");
    emitln("    CLR R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("fwrite:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 6(R4), R2");
    emitln("    MOV 8(R4), R3");
    emitln("    TST R2");
    emitln("    BEQ .Lfwrite_zero");
    emitln("    TST R3");
    emitln("    BEQ .Lfwrite_zero");
    emitln("    MOV R3, -(R6)");
    emitln("    MOV R2, -(R6)");
    emitln("    JSR R5, __mul");
    emitln("    ADD #4, R6");
    emitln("    MOV R0, R2");
    emitln("    MOV 10(R4), R0");
    emitln("    TST R0");
    emitln("    BEQ .Lfwrite_zero");
    emitln("    DEC R0");
    emitln("    MOV 4(R4), R1");
    emitln("    TRAP #22");
    emitln("    MOV 6(R4), R1");
    emitln("    CMP #1, R1");
    emitln("    BEQ .Lfwrite_ret");
    emitln("    MOV R1, -(R6)");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, __div");
    emitln("    ADD #4, R6");
    emitln(".Lfwrite_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");
    emitln(".Lfwrite_zero:");
    emitln("    CLR R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("fclose:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    TST R0");
    emitln("    BEQ .Lfclose_bad");
    emitln("    DEC R0");
    emitln("    TRAP #23");
    emitln("    BR .Lfclose_ret");
    emitln(".Lfclose_bad:");
    emitln("    MOV #0xFFFF, R0");
    emitln(".Lfclose_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("fseek:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    TST R0");
    emitln("    BEQ .Lfseek_bad");
    emitln("    DEC R0");
    emitln("    MOV 6(R4), R1");
    emitln("    MOV 8(R4), R2");
    emitln("    TRAP #24");
    emitln("    BR .Lfseek_ret");
    emitln(".Lfseek_bad:");
    emitln("    MOV #0xFFFF, R0");
    emitln(".Lfseek_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("ftell:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    TST R0");
    emitln("    BEQ .Lftell_bad");
    emitln("    DEC R0");
    emitln("    TRAP #25");
    emitln("    BR .Lftell_ret");
    emitln(".Lftell_bad:");
    emitln("    MOV #0xFFFF, R0");
    emitln(".Lftell_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("pdp11_set_bank:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    TRAP #26");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("fgetc:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emit_data_load("__rt_ungetc_has", "R1", "R2");
    emitln("    TST R1");
    emitln("    BEQ .Lfgetc_read");
    emit_data_load("__rt_ungetc_fp", "R1", "R2");
    emitln("    CMP R1, R0");
    emitln("    BNE .Lfgetc_read");
    emit_data_load("__rt_ungetc_ch", "R0", "R2");
    emit_data_clr("__rt_ungetc_has", "R2");
    emitln("    BR .Lfgetc_ret");
    emitln(".Lfgetc_read:");
    emitln("    TST R0");
    emitln("    BEQ .Lfgetc_stdin");
    emitln(".Lfgetc_file:");
    emitln("    MOV 4(R4), R0");
    emitln("    DEC R0");
    emitln("    MOV #__rt_fgetc_buf, R1");
    emitln("    MOV #1, R2");
    emitln("    TRAP #21");
    emitln("    CMP #1, R0");
    emitln("    BNE .Lfgetc_eof");
    emit_data_load_byte("__rt_fgetc_buf", "R0", "R1");
    emit_data_clr("__rt_feof_flag", "R1");
    emitln("    BR .Lfgetc_ret");
    emitln(".Lfgetc_eof:");
    emitln("    MOV #1, R0");
    emit_data_store("__rt_feof_flag", "R0", "R1");
    emitln("    MOV #0xFFFF, R0");
    emitln("    BR .Lfgetc_ret");
    emitln(".Lfgetc_stdin:");
    emitln("    TRAP #2");
    emitln("    CMP #0, R0");
    emitln("    BNE .Lfgetc_stdin_ok");
    emitln("    MOV #1, R0");
    emit_data_store("__rt_feof_flag", "R0", "R1");
    emitln("    MOV #0xFFFF, R0");
    emitln("    BR .Lfgetc_ret");
    emitln(".Lfgetc_stdin_ok:");
    emit_data_clr("__rt_feof_flag", "R1");
    emitln(".Lfgetc_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("getc:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, fgetc");
    emitln("    ADD #2, R6");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("fputc:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R1");
    emitln("    MOV 6(R4), R0");
    emitln("    TST R0");
    emitln("    BEQ .Lfputc_stdout");
    emitln("    DEC R0");
    emitln("    SUB #2, R6");
    emitln("    MOV R6, R2");
    emitln("    MOVB R1, (R2)");
    emitln("    MOV #1, R3");
    emitln("    MOV R2, R1");
    emitln("    MOV R3, R2");
    emitln("    TRAP #22");
    emitln("    ADD #2, R6");
    emitln("    CMP #0, R0");
    emitln("    BEQ .Lfputc_fail");
    emitln("    MOV 4(R4), R0");
    emitln("    BR .Lfputc_ret");
    emitln(".Lfputc_stdout:");
    emitln("    MOV 4(R4), R0");
    emitln("    TRAP #1");
    emitln("    MOV 4(R4), R0");
    emitln("    BR .Lfputc_ret");
    emitln(".Lfputc_fail:");
    emitln("    MOV #0xFFFF, R0");
    emitln(".Lfputc_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("putc:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    MOV 6(R4), R1");
    emitln("    MOV R1, -(R6)");
    emitln("    MOV R0, -(R6)");
    emitln("    JSR R5, fputc");
    emitln("    ADD #4, R6");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("fgets:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R1");
    emitln("    MOV 6(R4), R2");
    emitln("    MOV 8(R4), R3");
    emitln("    TST R2");
    emitln("    BEQ .Lfgets_null");
    emitln("    CMP #1, R2");
    emitln("    BNE .Lfgets_setup");
    emitln("    CLRB (R1)");
    emitln("    MOV R1, R0");
    emitln("    BR .Lfgets_ret");
    emitln(".Lfgets_setup:");
    emitln("    SUB #1, R2");
    emitln("    SUB #2, R6");
    emitln("    CLR -2(R4)");
    emitln(".Lfgets_next:");
    emitln("    TST R2");
    emitln("    BEQ .Lfgets_done");
    emitln("    MOV R1, -(R6)");
    emitln("    MOV R2, -(R6)");
    emitln("    MOV R3, -(R6)");
    emitln("    JSR R5, fgetc");
    emitln("    ADD #2, R6");
    emitln("    MOV (R6)+, R2");
    emitln("    MOV (R6)+, R1");
    emitln("    CMP #0xFFFF, R0");
    emitln("    BEQ .Lfgets_eof");
    emitln("    MOV #1, -2(R4)");
    emitln("    MOVB R0, (R1)+");
    emitln("    DEC R2");
    emitln("    CMP #0x000A, R0");
    emitln("    BEQ .Lfgets_done");
    emitln("    BR .Lfgets_next");
    emitln(".Lfgets_eof:");
    emitln("    TST -2(R4)");
    emitln("    BNE .Lfgets_done");
    emitln("    ADD #2, R6");
    emitln("    CLR R0");
    emitln("    BR .Lfgets_ret");
    emitln(".Lfgets_done:");
    emitln("    CLRB (R1)");
    emitln("    ADD #2, R6");
    emitln("    MOV 4(R4), R0");
    emitln("    BR .Lfgets_ret");
    emitln(".Lfgets_null:");
    emitln("    CLR R0");
    emitln(".Lfgets_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("ungetc:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV 4(R4), R0");
    emitln("    CMP #0xFFFF, R0");
    emitln("    BEQ .Lungetc_ret");
    emitln("    MOV 6(R4), R1");
    emit_data_store("__rt_ungetc_fp", "R1", "R2");
    emit_data_store("__rt_ungetc_ch", "R0", "R2");
    emitln("    MOV #1, R1");
    emit_data_store("__rt_ungetc_has", "R1", "R2");
    emit_data_clr("__rt_feof_flag", "R2");
    emitln(".Lungetc_ret:");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("feof:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emit_data_load("__rt_feof_flag", "R0", "R1");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("ferror:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emit_data_load("__rt_ferror_flag", "R0", "R1");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");

    emitln("fflush:");
    emitln("    MOV R4, -(R6)");
    emitln("    MOV R6, R4");
    emitln("    MOV #0, R0");
    emitln("    MOV R4, R6");
    emitln("    MOV (R6)+, R4");
    emitln("    RTS R5");
}
